FROM node:18-alpine AS make-sanafe

RUN apk add bash gcc g++ musl-dev python3 py3-pip python3-dev
RUN apk add make git

RUN mkdir /home/build_tutorial
RUN git clone https://github.com/SLAM-Lab/SANA-FE /home/build_tutorial/sana-fe
RUN cd /home/build_tutorial/sana-fe && make
RUN wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1WkbJZFasTe-v8vTYXrUaz_1e-p_xHMEj' -O /home/build_tutorial/dvs_challenge.npz

FROM node:18-alpine AS sanafe
RUN apk add vim diffutils
RUN apk add bash python3 py3-pip py3-yaml py3-numpy
RUN mkdir /tutorial

COPY --from=make-sanafe /home/build_tutorial/sana-fe/sim /
COPY --from=make-sanafe /home/build_tutorial/sana-fe/sim.py /
COPY --from=make-sanafe /home/build_tutorial/sana-fe/tutorial/setup_tutorial.sh /
COPY --from=make-sanafe /home/build_tutorial/dvs_challenge.npz /home/
COPY --from=make-sanafe /home/build_tutorial/sana-fe/tutorial/arch.yaml /home/
COPY --from=make-sanafe /home/build_tutorial/sana-fe/tutorial/loihi.yaml /home/
COPY --from=make-sanafe /home/build_tutorial/sana-fe/tutorial/snn.net /home/
COPY --from=make-sanafe /home/build_tutorial/sana-fe/tutorial/dvs_challenge.py /home/
COPY --from=make-sanafe /home/build_tutorial/sana-fe/tutorial/TUTORIAL.md /home/
COPY --from=make-sanafe /home/build_tutorial/sana-fe/tutorial/run.log /
COPY --from=make-sanafe /home/build_tutorial/sana-fe/tutorial/run_results /
COPY --from=make-sanafe /home/build_tutorial/sana-fe/tutorial/arch.log /
COPY --from=make-sanafe /home/build_tutorial/sana-fe/tutorial/arch_results /
COPY --from=make-sanafe /home/build_tutorial/sana-fe/tutorial/snn.log /
COPY --from=make-sanafe /home/build_tutorial/sana-fe/tutorial/snn_results /
COPY --from=make-sanafe /home/build_tutorial/sana-fe/tutorial/challenge.log /
COPY --from=make-sanafe /home/build_tutorial/sana-fe/tutorial/solutions/arch_completed.yaml /
COPY --from=make-sanafe /home/build_tutorial/sana-fe/tutorial/solutions/snn_completed.net /


RUN chmod 755 /setup_tutorial.sh
ENTRYPOINT exec /bin/bash -c "/setup_tutorial.sh & trap : TERM INT; sleep infinity & wait"
