name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install flex and bison (platform-specific)
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install bison flex
            echo 'PATH="/opt/homebrew/opt/bison/bin:/opt/homebrew/opt/flex/bin:$PATH"' >> $GITHUB_ENV
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            choco install winflexbison3
            echo 'C:\ProgramData\chocolatey\bin' >> $GITHUB_PATH
          fi

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.0.0
        # env:
        #   CIBW_SOME_OPTION: value
        #   ...
        with:
        #   package-dir: .
        #   output-dir: wheelhouse
          config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
